defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      layout: "post" # overrides previous default layout
domain: "cliffordwilliam.github.io"       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: "https://cliffordwilliam.github.io"  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: "/my_archive/"      # place folder name if the site is served in a subfolder
