# default layouts
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      layout: "post" # overrides previous default layout

# if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
domain: "cliffordwilliam.github.io"

# the base hostname and protocol for your site, e.g. http://example.com
url: "https://cliffordwilliam.github.io"

# place folder name if the site is served in a subfolder
baseurl: "/my_archive"

# custom
author_name: "Clifford William"
author_email: ccliffordwilliam@gmail.com
author_linkedin: https://www.linkedin.com/in/clifford-william-05bb4220b/